### ISSUE TITLE
Support for raygun "Affected User Tracking"

### ISSUE THREAD

**Issue by TonioOoOo** [plmwong/log4net-raygun#12]
Hy, Thank you for this beautiful appender!

With `RaygunClient` you can track [affected user](https://github.com/MindscapeHQ/raygun4net#affected-user-tracking)
```C#
_raygunClient.UserInfo = new RaygunIdentifierMessage("jason@mindscape.com")
{
  IsAnonymous = false,
  FullName = "Jason Fauchelle",
  FirstName = "Jason"
};
```

A solution is to resolve this issue: https://github.com/plmwong/log4net-raygun/issues/6
or do something like Tags: https://github.com/plmwong/log4net-raygun/issues/2

**Comment by plmwong** [comment]
Implemented this in release 4.2.0, so that you can store a `RaygunIdentifierMessage` into the Properties of log4net and have that be populated onto the 'Affected user' portion of the Raygun message.

I am also looking into allowing a custom RaygunClientFactory to be configured on the appender so that client construction is more customisable, which should help in cases where the `log4net.Raygun` implementation falls behind the configuration options for `Mindscape.Raygun`.
